
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twkxcgljyfccaxhelmun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3a3hjZ2xqeWZjY2F4aGVsbXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTE0NzMsImV4cCI6MjA1Nzg2NzQ3M30.hZsTlU_ZV2Z7aROwHGRxvnzAOZK_NMdl4hfiQBHnSyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Define basic database types for autocomplete (will be extended when using Supabase CLI to generate types)
export type Tables = {
  profiles: {
    id: string;
    username: string | null;
    full_name: string | null;
    avatar_url: string | null;
    default_currency: string;
    created_at: string;
    updated_at: string;
  };
  groups: {
    id: string;
    name: string;
    description: string | null;
    budget: number;
    created_at: string;
    created_by: string;
  };
  group_members: {
    id: string;
    group_id: string;
    user_id: string;
    joined_at: string;
  };
  expenses: {
    id: string;
    title: string;
    amount: number;
    date: string;
    category: string;
    currency: string;
    description: string | null;
    receipt_url: string | null;
    created_at: string;
    user_id: string;
    group_id: string | null;
  };
};
